### ISSUE TITLE
[Suggestion] Requesting more button customization and button combo

### ISSUE THREAD

**Issue by iAmErmac** [hh79/gzdoomvr#58]
Some buttons mapping are hardcoded (like trigger buttons) and cannot be mapped to other actions. eg. binding left trigger to alt-fire is not possible. Can we have less buttons mapped through codes and allow us the bindings on them through control settings?

Also QuestZDoom supports off-hand grip + any other button as combo to bind as new buttons. This is especially helpful when using a mod that requires way more action buttons (eg. separate buttons for melee, grenade, fly/swim up/down, inventory left/right, inventory item select, drop weapon/item etc.). Is it possible to add this feature in GZDoomVR? This will essentially double the number of mappable buttons in the controller.

Here's how the key bindings work in QuestZDoom:

Primary Button Functions:

A Button - Open Door / Switch
B Button - Jump
Y Button - Toggle AutoMap
X Button - Unmapped [Delete a button mapping in the menu]
Dominant-Hand Controller - Weapon orientation
Dominant-Hand Thumbstick - left/right Snap turn, up/down weapon change
Dominant-Hand Thumbstick click - Unmapped
Dominant-Hand Trigger - Fire Weapon
Dominant Grip Button - When held down, secondary button functions are available
Off-Hand Controller - Direction of movement (or if configured settings HMD direction is used)
Off-Hand Thumbstick - locomotion / teleport
Off-Hand Trigger - Run
Off-Hand Grip Button - Weapon Stabilization - two handed weapon mode
Off-Hand Thumbstick click - Unmapped

Secondary Button Functions:
Accessed by holding down the dominant hand grip button - All these can be reassigned in the options menu

A Button - Unmapped
B Button - Unmapped
Y Button - Unmapped
X Button - Unmapped
Dominant-Hand Thumbstick click - Unmapped
Dominant-Hand Trigger - Alt Fire Weapon
Off-Hand Trigger - Unmapped
Off-Hand Thumbstick click - Unmapped

**Comment by hh79** [comment]
Yes, that is a plan for fixing button problems. I want to align key bindings with QuestZDoom and to have possibility for play mods requring extra bindings. I will not probably implement two hand weapon grip though.  I have started working on it but I have to stop due to lack of time, but it is on the top of my to-do list.

**Comment by WMan22** [comment]
> Yes, that is a plan for fixing button problems. I want to align key bindings with QuestZDoom and to have possibility for play mods requring extra bindings. I will not probably implement two hand weapon grip though. I have started working on it but I have to stop due to lack of time, but it is on the top of my to-do list.

On the subject of control customization, is it possible to get a radial menu to select weapons with of some kind? That way it frees up a whole button, since you wouldn't need to have a weapon back and weapon forward, just one button for weapon selection. Would prefer to be able to customize it with more than just weapons though, you could just assign inputs in general to it, that way stuff like Hideous Destructor would even become viable to play in VR.

**Comment by knowsshit** [comment]
There are several weapon wheel add-ons for GZDoom, but I had problems finding anyone that would work good with GZDoomVR. The gearbox add-on at https://github.com/mmaulwurff/gearbox seemed promising, but it expects mouse inputs which in VR would be looking around instead of using the left stick to quickly select a weapon. Maybe there is some fix for that, or another weapon wheel that works better?

**Comment by Zod1234** [comment]
any updates on this?  combo binding and 2 handed weapons would be great.

**Comment by knowsshit** [comment]
I still haven't found any good solutions for it, so I am still stuck cycling weapons with the grab buttons.

There are a lot of weapons, so a weapon change takes a serious amount of time when it is needed the most later in the game when lots of stuff is going on.

Modding the gearbox selector wheel to work with a gamepad joystick instead of mouse input (or something similar) would be so nice. It would be just one button for bringing up the wheel and a quick positioning of the stick and release the button again to select. The game can even pause or slow down while the wheel is up.

**Comment by JennaScvl** [comment]
The inability to rebind triggers persists, and left trigger doesn't seem to be able to do anything. I can rebind right trigger with the console, but doing it to the left trigger seems to do nothing. It's rather infuriating.

Also I'd like to second the weapon selection radial menu. My suggestion would be to use the "HUD" graphics for the radial menu display because many mods exist that have their own weapons and number of weapons.

**Comment by iAmErmac** [comment]
At this point I'd suggest using Emawind's fork of QuestZDoom for PCVR. It has all the features from QuestZDoom and the dev is actively working on it and improving it weekly basis.
https://github.com/emawind84/QuestZDoom/releases
To contact the dev (Emawind) directly join Team Beef's discord, you can ask for better steamvr heaadset support and can even playtest the dev builds to help improving it
